### ISSUE TITLE
3. Sebagai user saya menginginkan adanya informas yang lengkap tentang produk yang dijual, agar memudahkn user dalam melihat dan memilih produk [10]

### ISSUE THREAD

**Issue by meidianijr** [meidianijr/rpl.kaulempung#3]
- [x] Membuat halaman katalog
- [x] Membuat atribut yang dibutuhkan katalog
- [x] Memasukkan produk ke katalog

**Comment by kendry01** [comment]
Ini udah masuk ya, buat login dan regist kalau berhasil pasti bisa masuk ke catalog ini
